events {}

http {
    server {
        listen 80;
        server_name localhost;

        # Nginx 상태 체크용 엔드포인트 추가
        location /nginx_status {
            stub_status on;
            access_log off;         # 상태 체크 요청에 대해 로그 남기지 않음
            allow all;        # 로컬에서만 접근 허용
        }

        # 실제 웹 애플리케이션 페이지 (리버스 프록시)
        location / {
            proxy_pass http://10.96.0.20:8080/;  # Tomcat index svc IP
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}

